# coding: utf-8

"""
    NEF_Emulator

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from evolved5g.swagger_client.api_client import ApiClient


class QoSInformationApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def read_qos_active_profiles_api_v1_qos_info_qos_profiles_gnb_id_get(self, g_nb_id, **kwargs):  # noqa: E501
        """Read Qos Active Profiles  # noqa: E501

        Get the available QoS Characteristics  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_qos_active_profiles_api_v1_qos_info_qos_profiles_gnb_id_get(g_nb_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str g_nb_id: (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.read_qos_active_profiles_api_v1_qos_info_qos_profiles_gnb_id_get_with_http_info(g_nb_id, **kwargs)  # noqa: E501
        else:
            (data) = self.read_qos_active_profiles_api_v1_qos_info_qos_profiles_gnb_id_get_with_http_info(g_nb_id, **kwargs)  # noqa: E501
            return data

    def read_qos_active_profiles_api_v1_qos_info_qos_profiles_gnb_id_get_with_http_info(self, g_nb_id, **kwargs):  # noqa: E501
        """Read Qos Active Profiles  # noqa: E501

        Get the available QoS Characteristics  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_qos_active_profiles_api_v1_qos_info_qos_profiles_gnb_id_get_with_http_info(g_nb_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str g_nb_id: (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['g_nb_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method read_qos_active_profiles_api_v1_qos_info_qos_profiles_gnb_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'g_nb_id' is set
        if ('g_nb_id' not in params or
                params['g_nb_id'] is None):
            raise ValueError("Missing the required parameter `g_nb_id` when calling `read_qos_active_profiles_api_v1_qos_info_qos_profiles_gnb_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'g_nb_id' in params:
            path_params['gNB_id'] = params['g_nb_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/qosInfo/qosProfiles/{gNB_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def read_qos_active_rules_api_v1_qos_info_qos_rules_supi_get(self, supi, **kwargs):  # noqa: E501
        """Read Qos Active Rules  # noqa: E501

        Get the available QoS Characteristics  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_qos_active_rules_api_v1_qos_info_qos_rules_supi_get(supi, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str supi: (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.read_qos_active_rules_api_v1_qos_info_qos_rules_supi_get_with_http_info(supi, **kwargs)  # noqa: E501
        else:
            (data) = self.read_qos_active_rules_api_v1_qos_info_qos_rules_supi_get_with_http_info(supi, **kwargs)  # noqa: E501
            return data

    def read_qos_active_rules_api_v1_qos_info_qos_rules_supi_get_with_http_info(self, supi, **kwargs):  # noqa: E501
        """Read Qos Active Rules  # noqa: E501

        Get the available QoS Characteristics  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_qos_active_rules_api_v1_qos_info_qos_rules_supi_get_with_http_info(supi, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str supi: (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['supi']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method read_qos_active_rules_api_v1_qos_info_qos_rules_supi_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'supi' is set
        if ('supi' not in params or
                params['supi'] is None):
            raise ValueError("Missing the required parameter `supi` when calling `read_qos_active_rules_api_v1_qos_info_qos_rules_supi_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'supi' in params:
            path_params['supi'] = params['supi']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/qosInfo/qosRules/{supi}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def read_qos_characteristics_api_v1_qos_info_qos_characteristics_get(self, **kwargs):  # noqa: E501
        """Read Qos Characteristics  # noqa: E501

        Get the available QoS Characteristics  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_qos_characteristics_api_v1_qos_info_qos_characteristics_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.read_qos_characteristics_api_v1_qos_info_qos_characteristics_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.read_qos_characteristics_api_v1_qos_info_qos_characteristics_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def read_qos_characteristics_api_v1_qos_info_qos_characteristics_get_with_http_info(self, **kwargs):  # noqa: E501
        """Read Qos Characteristics  # noqa: E501

        Get the available QoS Characteristics  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_qos_characteristics_api_v1_qos_info_qos_characteristics_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method read_qos_characteristics_api_v1_qos_info_qos_characteristics_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/qosInfo/qosCharacteristics', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
