# coding: utf-8

"""
    NEF_Emulator

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BodyCreateUserOpenApiV1UsersOpenPost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'password': 'str',
        'email': 'str',
        'full_name': 'str'
    }

    attribute_map = {
        'password': 'password',
        'email': 'email',
        'full_name': 'full_name'
    }

    def __init__(self, password=None, email=None, full_name=None):  # noqa: E501
        """BodyCreateUserOpenApiV1UsersOpenPost - a model defined in Swagger"""  # noqa: E501
        self._password = None
        self._email = None
        self._full_name = None
        self.discriminator = None
        self.password = password
        self.email = email
        if full_name is not None:
            self.full_name = full_name

    @property
    def password(self):
        """Gets the password of this BodyCreateUserOpenApiV1UsersOpenPost.  # noqa: E501


        :return: The password of this BodyCreateUserOpenApiV1UsersOpenPost.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this BodyCreateUserOpenApiV1UsersOpenPost.


        :param password: The password of this BodyCreateUserOpenApiV1UsersOpenPost.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def email(self):
        """Gets the email of this BodyCreateUserOpenApiV1UsersOpenPost.  # noqa: E501


        :return: The email of this BodyCreateUserOpenApiV1UsersOpenPost.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this BodyCreateUserOpenApiV1UsersOpenPost.


        :param email: The email of this BodyCreateUserOpenApiV1UsersOpenPost.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def full_name(self):
        """Gets the full_name of this BodyCreateUserOpenApiV1UsersOpenPost.  # noqa: E501


        :return: The full_name of this BodyCreateUserOpenApiV1UsersOpenPost.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this BodyCreateUserOpenApiV1UsersOpenPost.


        :param full_name: The full_name of this BodyCreateUserOpenApiV1UsersOpenPost.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BodyCreateUserOpenApiV1UsersOpenPost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BodyCreateUserOpenApiV1UsersOpenPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
