# coding: utf-8

"""
    NEF_Emulator

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LocationInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cell_id': 'str',
        'enode_b_id': 'str'
    }

    attribute_map = {
        'cell_id': 'cellId',
        'enode_b_id': 'enodeBId'
    }

    def __init__(self, cell_id=None, enode_b_id=None):  # noqa: E501
        """LocationInfo - a model defined in Swagger"""  # noqa: E501
        self._cell_id = None
        self._enode_b_id = None
        self.discriminator = None
        if cell_id is not None:
            self.cell_id = cell_id
        if enode_b_id is not None:
            self.enode_b_id = enode_b_id

    @property
    def cell_id(self):
        """Gets the cell_id of this LocationInfo.  # noqa: E501


        :return: The cell_id of this LocationInfo.  # noqa: E501
        :rtype: str
        """
        return self._cell_id

    @cell_id.setter
    def cell_id(self, cell_id):
        """Sets the cell_id of this LocationInfo.


        :param cell_id: The cell_id of this LocationInfo.  # noqa: E501
        :type: str
        """

        self._cell_id = cell_id

    @property
    def enode_b_id(self):
        """Gets the enode_b_id of this LocationInfo.  # noqa: E501


        :return: The enode_b_id of this LocationInfo.  # noqa: E501
        :rtype: str
        """
        return self._enode_b_id

    @enode_b_id.setter
    def enode_b_id(self, enode_b_id):
        """Sets the enode_b_id of this LocationInfo.


        :param enode_b_id: The enode_b_id of this LocationInfo.  # noqa: E501
        :type: str
        """

        self._enode_b_id = enode_b_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LocationInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LocationInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
