default_context:
    git_email: "GITHUB_EMAIL"
    repo_name: "REPOSITORY_NAME"
    remote_username: "GITHUB_USERNAME"
    token_repo: "GITHUB_TOKEN"
    netapp_name: "NETAPP_NAME"
    netapp_app: "vAPP_ NAME"
    netapp_service: "NETAPP_SERVICE"
    netapp_port: "NETAPP_PORT"
    netapp_target_port: "TARGET_PORT"
