default_context:
    git_email: "paula.encinar@atos.net"
    repo_name: "test3"
    remote_username: "pencinarsanz-atos"
    token_repo: "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"
    netapp_name: "test"
    netapp_app: "test"
    netapp_service: "test"
    netapp_port: "8080"
    netapp_target_port: "8080"
