name: deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          python3 setup.py install
      - name: Build and Upload to pypi
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
